[package]
name = "rymx"
version = "0.0.1"
edition = "2021"
default-run = "rymx"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.2", features = ["cargo"] }
owo-colors = "3"
rustyline = "11"
termsize = "0.1"
stringx.workspace = true

[features]
expand = []
