[package]
name = "rymx"
version = "0.0.1"
edition = "2021"
default-run = "rymx"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stringx.workspace = true
colored = "2.0.0"
rustyline = "10.0.0"
rym_ast.workspace = true
rym_lexer.workspace = true
rym_parser.workspace = true
rym_errors.workspace = true
rym_ast_passes.workspace = true
tree_walk.workspace = true

[features]
expand = []
