[package]
name = "rymx"
version = "0.0.1"
edition = "2021"
default-run = "rymx"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stringx.workspace = true
colored = "2.0.0"
rustyline = "10.0.0"
rym_ast = { path = "../rym_ast" }
rym_lexer = { path = "../rym_lexer" }
rym_parser = { path = "../rym_parser" }
rym_errors = { path = "../rym_errors" }
tree_walk = { path = "../tree_walk" }

[features]
expand = []
