[package]
name = "rymx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
rustyline = "10.0.0"
rym_ast = { path = "../rym_ast" }
rym_tree_walk = { path = "../rym_tree_walk" }
