[package]
name = "rymx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
rustyline = "10.0.0"
ast = { path = "../ast" }
tokenize = { path = "../tokenize" }
parse = { path = "../parse" }
tree_walk = { path = "../tree_walk" }
