[package]
name = "rymx"
version = "0.0.1"
edition = "2021"
default-run = "rymx"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
rustyline = "10.0.0"
ast = { path = "../ast" }
lex = { path = "../lex" }
parse = { path = "../parse" }
tree_walk = { path = "../tree_walk" }
stringx = "0.1.1"

[features]
expand = []
