[package]
name = "rym_tt"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol_str = "0.1.23"
rym_lexer = { path = "../rym_lexer" }
rym_span = { path = "../rym_span" }
