# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
	# Internal abstraction
	"crates/ast",

	# Abstraction implementations
	"crates/tokenize",
	"crates/parse",
	"crates/tree_walk",

	# Cli
	"crates/rymx",
]
