# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/ast", "crates/rymx", "crates/span"]
resolver = "2"
edition = "2024"

[workspace.dependencies]
ast = { path = "crates/ast" }
span = { path = "crates/span" }
stringx = "0.1"
thiserror = "1"
chumsky = { version = "0.11", features = ["pratt"] }
ariadne = "0.3"

# TODO is this really the fastest and smallest profile?
# smallest binary without compromising on speed
[profile.dist]
inherits = "release"
lto = "fat"

[profile.dev.package]
# smol_str.opt-level = 3
insta.opt-level = 3
similar.opt-level = 3
