# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
	"crates/ast",
	"crates/tokenize",
	"crates/parse",
	"crates/rym_tree_walk",
	"crates/rymx",
]
