# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
	# Global
	"crates/ast",
	"crates/rym_errors",
	"crates/rym_span",
	"crates/rym_tt",
	"crates/rym_unescape",

	# Parsing
	"crates/rym_lexer",
	"crates/rym_parser",
	"crates/lex",
	"crates/parse",

	# Evaluation
	"crates/tree_walk",

	# Cli
	"crates/rymx",

	# Integration Tests
	"crates/tests",
]

[workspace.dependencies]
rym_errors = { path = "crates/rym_errors" }
rym_lexer = { path = "crates/rym_lexer" }
rym_span = { path = "crates/rym_span" }
rym_tt = { path = "crates/rym_tt" }
rym_unescape = { path = "crates/rym_unescape" }
smol_str = "0.1.23"
stringx = "0.1.1"

[profile.dist]
inherits = "release"
lto = "fat"
panic = "abort"

[profile.dev.package]
smol_str.opt-level = 3
