# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
	# Types
	"crates/ast",
	"crates/rym_span",
	"crates/rym_tt",

	# Parsing
	"crates/rym_lexer",
	"crates/lex",
	"crates/parse",

	# Evaluation
	"crates/tree_walk",

	# Cli
	"crates/rymx",

	# Integration Tests
	"crates/tests",
]

[profile.dist]
inherits = "release"
lto = "fat"
panic = "abort"

# [profile.dev.package]
# smol_str.opt-level = 3
