# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
	# Internal abstraction
	"crates/ast",

	# Abstraction implementations
	"crates/lex",
	"crates/parse",
	"crates/tree_walk",

	# Cli
	"crates/rymx",

	# Integration Tests
	"crates/macros",
	"crates/tests",
]

[profile.dist]
inherits = "release"
lto = "fat"
panic = "abort"
