const std = @import("std");
const alloc = @import("alloc.zig");
const Header = alloc.Header;
const pointerSize = @sizeOf(usize);
var roots = std.ArrayList([*]u8).init(alloc.allocator);

export fn allocLayout(size: usize, typ: alloc.ObjType, maskOrPointer: usize) ?[*]u8 {
    const header = alloc.alloc(size) catch return null;
    header.typ = typ;
    header.maskOrPointer = maskOrPointer;
    return header.data().ptr;
}

export fn allocSliceOfPointers(size: usize) ?[*][*]u8 {
    return @ptrCast(@alignCast(allocLayout(size, .slice_of_pointers, 0)));
}

export fn allocSliceOfFatPointers(size: usize) ?[*][*]u8 {
    return @ptrCast(@alignCast(allocLayout(size, .slice_of_fat_pointers, 0)));
}

export fn addRoot(pointer: [*]u8) void {
    roots.append(pointer) catch @panic("Memory allocation error!");
}

export fn removeRoot(pointer: [*]u8) void {
    for (roots.items, 0..) |root, i| {
        if (root == pointer) {
            _ = roots.swapRemove(i);
            return;
        }
    }
}

export fn collectGarbage() void {
    for (roots.items) |root| {
        if (followDataPointer(root)) |header| {
            mark(header);
        }
    }

    sweep();
}

export fn mark(header: *Header) void {
    if (header.marked) {
        return;
    }
    header.marked = true;

    switch (header.typ) {
        .leaf => return,
        .slice_of_pointers => {
            const slice: [*][*]u8 = @ptrCast(@alignCast(header.data()));

            const len = header.len / pointerSize;
            for (0..len) |i| {
                const pointer = slice[i];
                if (followDataPointer(pointer)) |child| {
                    mark(child);
                }
            }
        },
        // else => mark_custom(header, @ptrCast(data)),
        else => {},
    }
}

// Generated by the compiler
extern fn markCustom(header: *Header) void;

fn sweep() void {
    var prev: ?*Header = null;
    var maybeNext = alloc.objects.next;
    var i: usize = 0;
    while (maybeNext) |next| {
        i += 1;
        const nextNext = next.next;

        if (next.marked) {
            next.marked = false;
            prev = next;
        } else {
            if (prev) |actualPrev| {
                actualPrev.next = next.next;
            } else {
                // First node deleted
                alloc.objects.next = next.next;
            }
            alloc.free(next);
        }
        maybeNext = nextNext;
    }
}

// Gets the corresponding header of a pointer pointing into the data section of an object
fn followDataPointer(pointer: [*]u8) ?*Header {
    const pointerInt = @intFromPtr(pointer);
    var maybeNext = alloc.objects.next;

    while (maybeNext) |next| {
        const data = next.data();
        const dataStart = @intFromPtr(data.ptr);
        const dataEnd = dataStart + data.len;
        if ((dataStart <= pointerInt) and (pointerInt <= dataEnd)) {
            return next;
        }
        maybeNext = next.next;
    }

    return null;
}

test "alloc and collect slice of pointers" {
    const leaf0 = allocLayout(4, .leaf, 0) orelse return;
    const leaf1 = allocLayout(16, .leaf, 0) orelse return;
    const slice = allocSliceOfPointers(pointerSize * 2) orelse return;

    slice[0] = leaf0;
    slice[1] = leaf1;

    addRoot(@ptrCast(slice));
    std.debug.print("{}", .{alloc.objects});

    collectGarbage();
    std.debug.print("{}", .{alloc.objects});

    try std.testing.expectEqual(roots.items.len, 1);
    try std.testing.expectEqual(alloc.objects.len(), 3);

    removeRoot(@ptrCast(slice));
    collectGarbage();
    std.debug.print("{}", .{alloc.objects});

    try std.testing.expectEqual(roots.items.len, 0);
    try std.testing.expectEqual(alloc.objects.len(), 0);
}
