const std = @import("std");
const alloc = @import("alloc.zig");
const Header = alloc.Header;
const pointerSize = @sizeOf(usize);

export fn allocLeaf(size: usize) ?[*]u8 {
    const header = alloc.alloc(size) catch return null;
    header.typ = .leaf;
    return header.data().ptr;
}

export fn allocSliceOfPointers(size: usize) ?[*][*]u8 {
    const header = alloc.alloc(size) catch return null;
    header.typ = .slice_of_pointers;
    return @ptrCast(@alignCast(header.data()));
}

export fn allocSliceOfFatPointers(_: usize) ?[*][*]u8 {
    // TODO
    return null;
}

export fn allocCustom(size: usize, typ: u32) ?[*]u8 {
    const header = alloc.alloc(size) catch return null;
    header.typ = @enumFromInt(typ);
    return header.data().ptr;
}

export fn addRoot(pointer: [*]u8) void {
    alloc.roots.append(pointer) catch @panic("Memory allocation error!");
}

export fn removeRoot(pointer: [*]u8) void {
    for (alloc.roots.items, 0..) |root, i| {
        if (root == pointer) {
            _ = alloc.roots.swapRemove(i);
            return;
        }
    }
}

export fn collectGarbage() void {
    for (alloc.roots.items) |root| {
        const header = followDataPointer(root);
        mark(header);
    }

    sweep();
}

export fn mark(header: *Header) void {
    if (header.marked) {
        return;
    }
    header.marked = true;

    switch (header.typ) {
        .leaf => return,
        .slice_of_pointers => {
            const slice: [*][*]u8 = @ptrCast(@alignCast(header.data()));

            const len = header.len / pointerSize;
            for (0..len) |i| {
                const pointer = slice[i];
                const child = followDataPointer(pointer);
                // std.debug.print("child: {}\n", .{child});

                mark(child);
            }
        },
        // else => mark_custom(header, @ptrCast(data)),
        else => {},
    }
}

// Generated by the compiler
extern fn markCustom(header: *Header) void;

fn sweep() void {
    outer: while (true) {
        for (alloc.objects.items, 0..) |header, i| {
            if (!header.marked) {
                alloc.free(header);
                _ = alloc.objects.swapRemove(i);
                continue :outer;
            }
        }

        break :outer;
    }

    for (alloc.objects.items) |header| {
        header.marked = false;
    }
}

// Gets the corresponding header of a pointer pointing into the data section of an object
fn followDataPointer(pointer: [*]u8) *Header {
    for (alloc.objects.items) |header| {
        const data = header.data();
        const dataStart = @intFromPtr(data.ptr);
        const dataEnd = dataStart + data.len;
        const pointerInt = @intFromPtr(pointer);
        if (dataStart >= pointerInt and pointerInt <= dataEnd) {
            return header;
        }
    }
    @panic("Corrupted pointers");
}

fn debugAllocations() void {
    std.debug.print("--- Debug\n", .{});

    for (alloc.objects.items) |header| {
        std.debug.print("{}\n", .{header});
    }
}

test "alloc and collect slice of pointers" {
    const leaf0 = allocLeaf(4) orelse return;
    const leaf1 = allocLeaf(16) orelse return;
    const slice = allocSliceOfPointers(pointerSize * 2) orelse return;

    slice[0] = leaf0;
    slice[1] = leaf1;

    addRoot(@ptrCast(slice));
    debugAllocations();

    collectGarbage();
    debugAllocations();

    removeRoot(@ptrCast(slice));
    collectGarbage();
    debugAllocations();

    try std.testing.expectEqual(alloc.roots.items.len, 0);
    try std.testing.expectEqual(alloc.objects.items.len, 0);
}
