const std = @import("std");
const alloc = @import("alloc.zig");
const Header = alloc.Header;
const Metadata = alloc.Metadata;
const pointerSize = @sizeOf(usize);

export fn allocLeaf(size: usize) ?[*]u8 {
    const parts = alloc.alloc(size) catch return null;
    parts.header.id = .leaf;
    return @ptrCast(parts.data);
}

export fn allocSliceOfPointers(size: usize) ?[*][*]u8 {
    const parts = alloc.alloc(size) catch return null;
    parts.header.id = .slice_of_pointers;
    return @ptrCast(@alignCast(parts.data));
}

export fn allocSliceOfFatPointers(_: usize) ?[*][*]u8 {
    // TODO
    return null;
}

export fn allocCustom(size: usize, typ: u32) ?[*]u8 {
    const parts = alloc.alloc(size) catch return null;
    parts.header.id = @enumFromInt(typ);
    return @ptrCast(parts.data);
}

export fn collectGarbage() void {
    for (alloc.all_metadata.items) |metadata| {
        mark(metadata.header, @ptrCast(metadata.data));
    }

    sweep();
}

// Generated by the compiler
extern fn mark_custom_type(header: *Header, data: [*]u8) void;

export fn mark(header: *Header, data: [*]u8) void {
    if (header.marked) {
        return;
    }

    switch (header.id) {
        .leaf => return,
        .slice_of_pointers => {
            const slice: [*][*]u8 = @ptrCast(@alignCast(data));

            const len = header.len / pointerSize;
            for (0..len) |i| {
                const child_data = slice[i];
                const child_header: *Header = @ptrCast(@alignCast(child_data - @sizeOf(Header)));
                // std.debug.print("data: {any}, header: {}\n", .{ child_data, child_header });

                mark(child_header, child_data);
                child_header.marked = true;
            }
        },
        // else => mark_custom_type(header, @ptrCast(data)),
        else => {},
    }
}

fn sweep() void {
    outer: while (true) {
        for (alloc.all_metadata.items, 0..) |metadata, i| {
            if (!metadata.header.marked) {
                alloc.free(metadata);
                _ = alloc.all_metadata.swapRemove(i);
                continue :outer;
            }
        }

        break :outer;
    }

    for (alloc.all_metadata.items) |metadata| {
        metadata.header.marked = false;
    }
}

fn debugAllocations() void {
    std.debug.print("--- Debug\n", .{});

    for (alloc.all_metadata.items) |metadata| {
        std.debug.print("{}\n", .{metadata.header});
    }
}

test "iter allocations" {
    const leaf0 = allocLeaf(4) orelse return;
    const leaf1 = allocLeaf(16) orelse return;
    const slice = allocSliceOfPointers(pointerSize * 2) orelse return;

    slice[0] = leaf0;
    slice[1] = leaf1;

    debugAllocations();

    collectGarbage();

    debugAllocations();
}
