[package]
name = "tree_walk"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rym_ast = { path = "../rym_ast" }
rym_parser = { path = "../rym_parser" }
thiserror = "1.0.37"
