<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>name</key>
		<string>Rym</string>
		<key>scopeName</key>
		<string>source.rym</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#block-comments</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#comments</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#keywords</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#punctuation</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#strings</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#chars</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#constants</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#function_declaration</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#function_name</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#ident</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>comments</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>documentation comments</string>
						<key>name</key>
						<string>comment.line.documentation.rym</string>
						<key>match</key>
						<string>^\s*///.*</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>line comments</string>
						<key>name</key>
						<string>comment.line.double-slash.rym</string>
						<key>match</key>
						<string>\s*//.*</string>
					</dict>
				</array>
			</dict>
			<key>block-comments</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>empty block comments</string>
						<key>name</key>
						<string>comment.block.rym</string>
						<key>match</key>
						<string>/\*\*/</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>block documentation comments</string>
						<key>name</key>
						<string>comment.block.documentation.rym</string>
						<key>begin</key>
						<string>/\*\*</string>
						<key>end</key>
						<string>\*/</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#block-comments</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>comment</key>
						<string>block comments</string>
						<key>name</key>
						<string>comment.block.rym</string>
						<key>begin</key>
						<string>/\*(?!\*)</string>
						<key>end</key>
						<string>\*/</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#block-comments</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>constants</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>decimal integers and floats</string>
						<key>name</key>
						<string>constant.numeric.decimal.rym</string>
						<key>match</key>
						<string>\b\d[\d_]*(\.?)[\d_]*(?:(E)([+-])([\d_]+))?(f\d+|i\d+|isize|u\d+|usize)?\b</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.separator.dot.decimal.rym</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>keyword.operator.exponent.rym</string>
							</dict>
							<key>3</key>
							<dict>
								<key>name</key>
								<string>keyword.operator.exponent.sign.rym</string>
							</dict>
							<key>4</key>
							<dict>
								<key>name</key>
								<string>constant.numeric.decimal.exponent.mantissa.rym</string>
							</dict>
							<key>5</key>
							<dict>
								<key>name</key>
								<string>entity.name.type.numeric.rym</string>
							</dict>
						</dict>
					</dict>
					<dict>
						<key>comment</key>
						<string>booleans</string>
						<key>match</key>
						<string>\b(True|False)\b</string>
						<key>name</key>
						<string>constant.language.bool.rym keyword.other.rym</string>
					</dict>
				</array>
			</dict>
			<key>function_declaration</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>\b(func|proc)\b</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>storage.type.fn.rym keyword.other.rym</string>
							</dict>
						</dict>
						<key>end</key>
						<string>(\{)|(?=\/\/|\n|\r)</string>
						<key>endCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.block.begin.rym</string>
							</dict>
						</dict>
						<key>name</key>
						<string>meta.function.signature.rym</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#function_declaration</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#function_name</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>function_name</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>([_a-z][_a-zA-Z0-9]*)(?=\s*\()</string>
						<key>name</key>
						<string>entity.name.function.rym</string>
					</dict>
					<dict>
						<key>match</key>
						<string>([_a-z][_a-zA-Z0-9]*)\s*((?=&lt;.*&gt;\()|(?=\())</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>entity.name.function.rym</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>keyword.operator.assignment.rym</string>
							</dict>
						</dict>
					</dict>
				</array>
			</dict>
			<key>ident</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>([A-Z]|_+[A-Z])[_a-zA-Z0-9]*</string>
						<key>name</key>
						<string>entity.name.rym</string>
					</dict>
					<dict>
						<key>match</key>
						<string>[_a-z][_a-zA-Z0-9]*</string>
						<key>name</key>
						<string>variable.name</string>
					</dict>
				</array>
			</dict>
			<key>keywords</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>keyword.other.rym</string>
						<key>match</key>
						<string>\b(func|proc|use|mod|pub|self|Self|as|move)\b</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.control keyword.other.rym</string>
						<key>match</key>
						<string>\b(impl|trait|type)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>control flow keywords</string>
						<key>name</key>
						<string>keyword.control.rym</string>
						<key>match</key>
						<string>\b(loop|while|do|for|in|match|with|if|then|else|return|break|continue)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>storage keywords</string>
						<key>name</key>
						<string>keyword.other.rym storage.type.rym</string>
						<key>match</key>
						<string>\b(let|mut|const)\b</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>logical operators</string>
						<key>name</key>
						<string>keyword.operator.logical.rym</string>
						<key>match</key>
						<string>(\||\|\||&amp;|&amp;&amp;|&lt;&lt;|&gt;&gt;|!)(?!=)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>single equal</string>
						<key>name</key>
						<string>keyword.operator.assignment.equal.rym</string>
						<key>match</key>
						<string>(?&lt;![&lt;&gt;])=(?!=|&gt;)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>comparison operators</string>
						<key>name</key>
						<string>keyword.operator.comparison.rym</string>
						<key>match</key>
						<string>(=(=)?(?!&gt;)|!=|&lt;=|(?&lt;!=)&gt;=)</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>math operators</string>
						<key>name</key>
						<string>keyword.operator.math.rym</string>
						<key>match</key>
						<string>[+\-*/%]=?</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>less than, greater than (special case)</string>
						<key>match</key>
						<string>(?:\b|(?:(\))|(\])|(\})))[ \t]+([&lt;&gt;])[ \t]+(?:\b|(?:(\()|(\[)|(\{)))</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.brackets.round.rym</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>punctuation.brackets.square.rym</string>
							</dict>
							<key>3</key>
							<dict>
								<key>name</key>
								<string>punctuation.brackets.curly.rym</string>
							</dict>
							<key>4</key>
							<dict>
								<key>name</key>
								<string>keyword.operator.comparison.rym</string>
							</dict>
							<key>5</key>
							<dict>
								<key>name</key>
								<string>punctuation.brackets.round.rym</string>
							</dict>
							<key>6</key>
							<dict>
								<key>name</key>
								<string>punctuation.brackets.square.rym</string>
							</dict>
							<key>7</key>
							<dict>
								<key>name</key>
								<string>punctuation.brackets.curly.rym</string>
							</dict>
						</dict>
					</dict>
				</array>
			</dict>
			<key>punctuation</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>comment</key>
						<string>dot</string>
						<key>name</key>
						<string>punctuation.dot.rym</string>
						<key>match</key>
						<string>\.</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>comma</string>
						<key>name</key>
						<string>punctuation.comma.rym</string>
						<key>match</key>
						<string>,</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>colon</string>
						<key>name</key>
						<string>punctuation.colon.rym</string>
						<key>match</key>
						<string>:</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>semicolon</string>
						<key>name</key>
						<string>punctuation.semi.rym</string>
						<key>match</key>
						<string>;</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>at</string>
						<key>name</key>
						<string>punctuation.at.rym</string>
						<key>match</key>
						<string>@</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>question mark</string>
						<key>name</key>
						<string>punctuation.question.rym</string>
						<key>match</key>
						<string>\?</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>thin arrow</string>
						<key>name</key>
						<string>punctuation.rym</string>
						<key>match</key>
						<string>-&gt;</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>fat arrow</string>
						<key>name</key>
						<string>punctuation.rym</string>
						<key>match</key>
						<string>=&gt;</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>curly braces</string>
						<key>name</key>
						<string>punctuation.brackets.curly.rym</string>
						<key>match</key>
						<string>[{}]</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>parentheses, round brackets</string>
						<key>name</key>
						<string>punctuation.brackets.round.rym</string>
						<key>match</key>
						<string>[()]</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>square brackets</string>
						<key>name</key>
						<string>punctuation.brackets.square.rym</string>
						<key>match</key>
						<string>[\[\]]</string>
					</dict>
					<dict>
						<key>comment</key>
						<string>angle brackets</string>
						<key>name</key>
						<string>punctuation.brackets.angle.rym</string>
						<key>match</key>
						<string>(?&lt;!=)[&lt;&gt;]</string>
					</dict>
				</array>
			</dict>
			<key>strings</key>
			<dict>
				<key>name</key>
				<string>string.quoted.double.rym</string>
				<key>begin</key>
				<string>"</string>
				<key>end</key>
				<string>"</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>constant.character.escape.rym</string>
						<key>match</key>
						<string>\\.</string>
					</dict>
				</array>
			</dict>
			<key>chars</key>
			<dict>
				<key>name</key>
				<string>string.quoted.single.rym</string>
				<key>begin</key>
				<string>'</string>
				<key>end</key>
				<string>'</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>constant.character.escape.rym</string>
						<key>match</key>
						<string>\\.</string>
					</dict>
				</array>
			</dict>
		</dict>
	</dict>
</plist>
