[package]
name = "rym_errors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rym_span.workspace = true
stringx.workspace = true
annotate-snippets = { version = "0.9", features = ["color"] }
