[package]
name = "rym_tree_walk"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = { path = "../ast" }
rym_ast = { path = "../rym_ast" }
